target 'PhoenixPlatform-iOS-SDK', :exclusive => true do
  pod "PhoenixPlatform-iOS-SDK", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "PhoenixPlatform-iOS-SDK", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
